### PR TITLE
pgrouting marketing brochure

### PR DESCRIPTION
**Pull request by cvvergara**
I am working on the pgRouting brochure,
This is a Work in progress.

I started to make a brochure/flyer, for pgRouting
I can see the brochure when using inskape, but in the uploaded file things don't show up.
https://github.com/pgRouting/osgeo/blob/pgRouting/marketing/print/pgRouting_a4.svg
What am I doing wrong?
I (almost) followed the commands shown here:
https://github.com/pgRouting/osgeo/wiki#instructions
Except that I used the zoo-project branch in luca's forks

ininskape

### CODE REVIEW

**Comment by jodygarnett** [comment]
We found out it is a technical limitation of inkscape. Inkscape uses "flow" text, but browsers only support a different kind of text. Inkscape apparently lets you convert but I have not understood how yet.

Inscape (when it works) uses flow spans - but no browsers can render them.

```
<flowRoot>
  <flowRegion>
  <rect id="rect4770"width="283.24115" height="228.32214" x="305.29822" y="179.84657"/>
  <flowPara>OSGeo holds a passionate belief in open source as the best way to build software ...</flowPara>
  <flowPara>This approach provides greater control than proprietary (closed) software ...</flowPara>
</flowRoot>

```

The other programs support tspans 

```
  <text>
    <tspan>Open Source</tspan>
    <tspan>Geospatial Foundation</tspan>
  </text>
```

**Comment by jodygarnett** [comment]
I have tried using https://boxy-svg.com/ and it kind of works

**Comment by cvvergara** [comment]
@jodygarnett 
Then its a browser problem...
The brochure wont be in a browser, it would be printed, right?
So, the Q now, if the software that is going to be used for printing the brochure will have the same problem as the browser?

**Comment by jodygarnett** [comment]
Sort of - except every other software I have found works the other way.

Inkscape uses a new version of the spec which nothing can handle. We would. We'd to ask inscape to output at EPS for printing. You can try it yourself and preview.

**Comment by cvvergara** [comment]
@jodygarnett 
I could print it, and I could create a pdf
https://github.com/pgRouting/osgeo/blob/a0a151b91c63903a4d2baff3187d76ae7a4f9eb2/marketing/print/pgRouting_a4.pdf
the other format EPS, I could create it but looks ugly.

**Comment by lucadelu** [comment]
- [ ] Bullets green triangle are bigger than the original ones
- [ ] Some text seems different format from the OSGeo one

**Comment by cvvergara** [comment]
@lucadelu 
The font is just bigger. But its the Sintony Font.

font

**Comment by lucadelu** [comment]
ok, it is Sintony. I don't like to much so big.

I'm going to add the pdf to the printable sheet for FOSS4G in Boston, but I would like if the text will be modified.

**Comment by cvvergara** [comment]
@lucadelu 
I used as base the one you had for zoo in your fork.
I did wonder why it was A4.
Q, is it how you like it then?
In the pgRouting team we decided for large font on the core functions.
But than being said, I will reduce the font, due to the fact that "letter" is smaller than A4, and it wont look so empty.

**Comment by cvvergara** [comment]
@lucadelu 
I added a letter version, svg & pdf

**Pull request merged**
