### PR TITLE
GRASS GIS flyer de

### PR DESCRIPTION
**Pull request by neteler**
German translation of OSGeo GRASS GIS flyer

### CODE REVIEW

**Comment by neteler** [comment]
For a PDF of the DE flyer, see https://data.neteler.org/tmp/grass_a4_DE.pdf

**Comment by neteler** [comment]
Ping - what is going to happen with the submitted PR(s)?

**Comment by jodygarnett** [comment]
Can we match the new folder structure, which separates out printable PDFs from the one page source material used to generate the PDFs. 

https://github.com/OSGeo/osgeo/tree/master/marketing/collateral/one-page-info

https://github.com/OSGeo/osgeo/tree/master/marketing/print/one-page-info

**Comment by jodygarnett** [comment]
For comparison please see:

- https://github.com/OSGeo/osgeo/blob/master/marketing/print/one-page-info/us/grass_letter.pdf
- https://github.com/OSGeo/osgeo/blob/master/marketing/print/one-page-info/eu/grass_gis_a4.pdf

**Comment by jodygarnett** [comment]
@neteler for the suggested de translation https://data.neteler.org/tmp/grass_a4_DE.pdf can you make a pull request for the https://github.com/OSGeo/osgeo/tree/master/marketing/print/one-page-info/de folder?

**Comment by neteler** [comment]
First marketing/collateral/one-page-info/grass-gis/de/grass_gis_a4_DE.svg needs to set to correct A4 size... this didn't happen yet

**Comment by neteler** [comment]
Done, see PR at https://github.com/OSGeo/osgeo/pull/127

**Pull request merged**
