### PR TITLE
incubator application questionnaire version 2.0 draft

### PR DESCRIPTION
**Pull request by jodygarnett**
Updated based on video meeting discussion:

* [version 2.0 draft](https://github.com/jodygarnett/osgeo/blob/incubation_questionair/incubation/documents/incubator_application_questionnaire.pdf)

Official version 1.0 document:
* [version 1.0](https://github.com/OSGeo/osgeo/blob/master/incubation/documents/incubator%20application%20questionnaire.pdf) (pdf)
* https://www.osgeo.org/resources/incubator-application-1-0/ (resource page, pdf download)
* https://www.osgeo.org/about/committees/incubation/application/ (legacy page, content moved to resource pdf above)

### CODE REVIEW

**Comment by jodygarnett** [comment]
I suspect that the questions could be sorted a bit to group topics together more smoothly. 

Get all the introductions out of the way early, then project descriptions, etc...

**Comment by kalxas** [comment]
Perhaps change the date of the v2.0 document to 2023?

**Comment by gdt** [comment]
This is a bikeshed kind of comment, but it would be nice to have this be markdown or equivalent instead of a non-diffable format.   (But at least it is odt and not  a proprietary format!)

**Comment by jodygarnett** [comment]
> This is a bikeshed kind of comment, but it would be nice to have this be markdown or equivalent instead of a non-diffable format. (But at least it is odt and not a proprietary format!)

We are trying to have official logos and so on official stuff. We can make a markdown for cut and paste like we did for incubation checklist.

**Comment by gdt** [comment]
> > This is a bikeshed kind of comment, but it would be nice to have this be markdown or equivalent instead of a non-diffable format. (But at least it is odt and not a proprietary format!)
> 
> We are trying to have official logos and so on official stuff. We can make a markdown for cut and paste like we did for incubation checklist.

I am pretty sure markdown can include the logo and a markdown-to-whatever can render it.  But if it's hard, don't worry about me; I really did mean "this is a bikeshed kind of comment".

**Comment by jodygarnett** [comment]
> I am pretty sure markdown can include the logo and a markdown-to-whatever can render it. But if it's hard, don't worry about me; I really did mean "this is a bikeshed kind of comment".

It is more I spent too much time in the marketing committee focused on branding :)

From a lower barrier to entry having the markdown for cut and paste is a good action.

**Comment by neteler** [comment]
FWIW, here converted with `pandoc` to MD:

# Incubator Application

- Version: 2.0
- Status: Draft
- DATE: August 16, 2006

## Questionnaire

# Purpose

The purpose of this questionnaire is to gather information from projects
teams wishing to join the OSGeo Foundation as a committee. Project teams
accepted into incubation are assigned a mentor for guidance in meeting
the incubation requirements.

Projects are required to be first recognized as an OSGeo Community
project, complete with OSGeo website page. Applicants are encouraged to
provide detailed answers below.

## Questions

1.  Provide the name and email address of the project owner and co-owners (if applicable).

2.  Introduce your project team including the name, email and organization for all committers.

3.  Who is your incubation mentor (or are you seeking a volunteer)?\
    *It can take some time to locate a suitable mentor. If you already have a volunteer in mind it greatly assist the application process.*

4.  Please provide link to project page on OSGeo website.\
    *Double check page is complete with:*
    -   Project description
    -   Type of application this project represents
    -   Relationships with other open source projects
    -   Open source license(s) used for source code
    -   Downloads to confirmation project has made an official release
    -   Project support of open standards

5.  Why is this project team applying to join OSGeo Foundation?

6.  Please describe any relationships with commercial companies or products.

7.  What is the origin / history of your project?\
    *Commercial, experimental, academic, research, government, or some other source?*

8.  If the project is listed as supporting an open standard - has the team obtained certification (or intends to seek certification)?

9.  Is the project technology covered by patents (and who owns these patents)?

10.  Is the project name, or technologies, covered by trademark (and who owns the trademark)?

11.  Does your team control the copyright for your project source code and documentation?

12.  How actively used is your project or technology?\
    *Example number of users, downstream applications, prominent websites, inclusion in distributions.*

13.  How many people actively contribute to the project at this time?\
    *Contributions include code, documentation, community building, ...*

14. How many people have commit access to the source code repository?

15. What are the drivers for your project -- share how your project/technology is used by the public?\
    *Include use by government, commercial, enthusiast, academic, research, aid, ...*

16. Does the project presently include automated build and quality assurance?

17. What programming languages are used by this project?

18. What is the primary written language(s) of the project team?\
    *Example English, French, Spanish, German, \...*

**Comment by jodygarnett** [comment]
> Under "describe commercial", add: If any company employs or has control over 25% or more steering committee members, committers, or any other group with authority, explain in detail the governance issues

We are attempting to ask projects what they have in place now - many of these topics will be worked on during incubation process. A common example is moving from company control and establishing a steering committee and governance.

**Comment by jodygarnett** [comment]
The app store issue may or may not be a concern based on distribution model compatibility with opensource license chosen. 

Once again this is advocacy and outreach so we do not want to scare folks with requirements that they can address during incubation process.

**Comment by jodygarnett** [comment]
> For "Does your team control the copyright", I think we need more. 

I do not think we need much more, this is fact findings 

I considered “Free and open source licenses depend on control of copyright for enforcement. How is copyright manages in your project?”

**Comment by jodygarnett** [comment]
I think some of this can be thrown out if we assume earlier “osgeo community” step has been taken. 

----

The incubation process is available to projects that have joined the osgeo community program as a recognition of excellence, trust, and respect of OSGeo values. Successfully competing incubation will recognize your project team as a full OSGeo committee. 

1. Has your project joined the OSGeo community program?

**Comment by gdt** [comment]
> > For "Does your team control the copyright", I think we need more.
> 
> I do not think we need much more, this is fact findings
> 
> I considered “Free and open source licenses depend on control of copyright for enforcement. How is copyright manages in your project?”

We obviously have philosophical differences but this is more.  "Does your team control the copyrigtht" is s a very confusing question and I do not expect anyone at all to really understand it.    On a non-geo project I maintain, I am really clear on how it works, and on licensing issues - but I still don't know whether I should answer yes or no.    The key question in open source is whether there is a CLA or not.  CLAs are a huge source of friction, and with corporate control, dangerous.    You talk about "respecting OSGeo values", but in my view copyright assignment to a company that can proprietarize is totally inconsistent with values.

So if you want to tone down the shoulds, and just ask.:

How do you handle copyright issues:
  - inbound=outbound
  - inbound=outbound and DCO
  - CLA  without copyright assignment (attach, and specify the counterparty)
  - copyright assignment (attach, and specify the counterparty)

then I think that's fine.

**Comment by jodygarnett** [comment]
Good discussion:
> 
> How do you handle copyright issues:

I think this is the question “How does your team manage copyright of your source code and documentation?”

We not wish to presume they handle it at all yet :) it may be a topic they need help on. 

Based on the answer we should learn a lot.

**Comment by gdt** [comment]
I think it would be good first to have the criteria for the "osgeo community" step, "begin incubation" step, and "graduate incubation".   That seems to be a major area of disagreement and/or confusion.  I see your point about projects that don't understand yet, but I see corporate projects that do understand and are misaligned as a more serious issue.

**Comment by jodygarnett** [comment]
The harder we work on this - the more I am thinking it is not a good document for osgeo in 2023. I do like use markdown to make it easier for projects to copy and paste into their own wiki.

I expect we should create a single document to cover 1) osgeo website 2) osgeo community 3) osgeo project 

You can see the progression:
- here for discussion https://www.osgeo.org/about/committees/incubation/
- here for requirements https://wiki.osgeo.org/wiki/Incubation_Committee#Step_1:_Add_OSGeo_Website_Project_Page

I am going to close this and await further discussion on the email list.

**Pull request closed without merging**
