### PR TITLE
gvSIG flyers uploading

### PR DESCRIPTION
**Pull request by mcarrera77**
We have uploaded the gvSIG flyers to the server.

### CODE REVIEW

**Comment by jodygarnett** [comment]
@mcarrera77 looking closely it looks like the gvSig logo background may be as you intended? Do you have a vector SVG image to use as a source (as the image provided would not look good when printed out).

gvsig-feedback

**Comment by mcarrera77** [comment]
Hi Jody,

what viewer are you using to print it? We can see the PDF file in 
Acrobat Reader and the SVG file in Inkscake without that background.

We also can see OSGeo logo without problem in both files.

About the 'Laptop frame' issue, what are you referring to? They are 
screenshots that are a summarize about what they can do.

Thank you very much.
Best regards,
   Mario

**Comment by jodygarnett** [comment]
I was using:

- github preview in safari and chrome
- macOS preview, downloading the above file to double check

For the laptop frame, the visual look for these handouts is to surround screen snaps with a frame of either a "laptop", "browser", or "mobile" as appropriate. 

- [marketing/photos](https://github.com/OSGeo/osgeo/tree/master/marketing/photos) - has the laptop frame as transparent PNG for use in SVG files, ideally we could make an SVG clipart 
- [grass_gis_a4.pdf](https://github.com/OSGeo/osgeo/blob/master/marketing/print/one-page-info/eu/grass_gis_a4.pdf) - is an example of how this looks

**Comment by mcarrera77** [comment]
We've updated the flyer. I attach it. 
[gvSIG_flyer2-def_A4.pdf](https://github.com/OSGeo/osgeo/files/2615787/gvSIG_flyer2-def_A4.pdf)

**Comment by jodygarnett** [comment]
You may want to just link to the pull request? Is there a pull request ...

**Pull request merged**
