### PR TITLE
Gsoc poster

### PR DESCRIPTION
**Pull request by cvvergara**
@jodygarnett 

This PR has the OSGeo-GSoC posters with sizes:
A0, A2, A4 and letter.
I created the pdf files for systems/people that don't have inkscape

Made it using inkscape (has a readme)
https://github.com/pgRouting/osgeo/tree/gsoc-poster/marketing/collateral/one-page-info/osgeo-gsoc-program

I wonder if this can be merged on tuesday, we can workout the details later (except logos, I am sending a mail)
The GSoC mentor summit is Friday, October 13 - Sunday, October 15, and I would like Madie & Rohith to have links to this files, in case they need them.

### CODE REVIEW

**Comment by cvvergara** [comment]
Mail requesting Logo review:
https://lists.osgeo.org/pipermail/discuss/2017-October/036394.html

**Comment by cvvergara** [comment]
Vicky,

This is as far as my editing capabilities can go.
The png logo is in a table in a Word document along with the aligned text.
My graphics guy is unavailable until Tuesday.
I will hope you might be able to work with this in some fashion.
I’m at a loss for more until Tuesday.

-Patrick

Task:
- [ ] Modify logo following example from Patrick

**Comment by PJHogan** [comment]
Vicky, much appreciated!

**Comment by cvvergara** [comment]
@PJHogan 
Your welcome

**Comment by jodygarnett** [comment]
feedback and ideas based on review of osgeo-gsoc-A0.pdf
- the text "make a calendar" is not centered in its pie slice and appears cut off.
- the text "listen to community" is too long for its pie slice and is extending to the next section
- I kind of liked an earlier version where the outer shapes mirrored the osgeo compass logo with a sawtooth "___/| ___/|" patten, the current pattern "\__/\__/\__/" looks great, but makes the logo shape in the middle look odd/inconsistent.
- I think "ZOO" may be "ZOO Project" but I am not sure
- What fonts are used? Did you stick to the [two osgeo fonts](https://github.com/OSGeo/osgeo/tree/master/marketing/branding/fonts) - or did you have a requirement to use a Google Summer of Code font? I think I count 4 different text presentations, the all caps "BE PROACTIVE" threw me off.
- If you wanted more colors for the outer wheel the [style guide](https://github.com/OSGeo/osgeo/blob/master/marketing/branding/styleguide-osgeo.pdf) now has secondary colors for use in cartography and diagrams such as the one you are making here


This is feedback / discussion rather than a PR review; nothing above would prevent merging this pull request.

**Comment by cvvergara** [comment]
## tasks
- [ ] Center "make a calendar"

## Comments
- Listen to community
  - is too long, I tried to reduce the font size of only that text, but looks like Its all or nothing.
  - I have an idea of how to tackle this, but it will take more time, I am opening an issue on my fork  https://github.com/pgRouting/osgeo/issues/28
- Pattern, @jodygarnett You mean like this one?
  https://mail.google.com/mail/u/0/#search/label%3Agsoc+poster/15dcc8601fc19c26?projector=1
  I can't put a link the the osgeo-gsoc-mentor maillist, but if you see the thread started on august 10: I was told:
  "I'm afraid the current design breaks the branding guidelines."
And immediately after, you sent me this files for inspiration:
https://drive.google.com/file/d/0B022m344wU7hdkNBSjJ4cHhRRzg/view
https://drive.google.com/file/d/0B022m344wU7hQU5WSFFkcGRFVjg/view
After that I removed everything that broke the guidelines
https://mail.google.com/mail/u/0/#search/label%3Agsoc+poster/15dcc8601fc19c26?projector=1
As no one complained of that removal, I thought: I was "modifying the logo" by using by using the pattern of the logo. So I made the other pattern.
- Zoo yes I think is Zoo project and its the logo I have (I got it from OSGeoLive logos)
- Fonts
  - "Success with", "Become an Open Source Developer", "Be Proactive" et all titles are Miriam Libre (I think I read on the guidelines)
  - All other text is Sintony
- About colours:
  - @lucadelu was the one in charge of checking and fixing using the Guidelines colours

**Comment by lucadelu** [comment]
Yes I checked before, I didn't check the last version and I just saw the new boxes in the bottom of the poster, I quite sure that "Coding" box is using some strange color (for example the red). I will fix the color boxes in the afternoon (CEST time)

**Comment by lucadelu** [comment]
Done, pull request here https://github.com/pgRouting/osgeo/pull/29

**Comment by jodygarnett** [comment]
Thanks @cvvergara, I fixed the pattern comment to be ``___/| ___/|`` patten, and ``\__/\__/\__/`` (was using the wrong markdown so it did not display correctly.

I remember the conversation, I think Vaclav Petras, he is not a member of the marketing committee - perhaps he was referencing the 52n logo branding guidelines?

Personally I like your poster for pushing creatively against the branding guidelines and seeing what is possible.

**Pull request merged**
