### PR TITLE
Improved consistency for QGIS flyer

### PR DESCRIPTION
**Pull request by anitagraser**

### CODE REVIEW

**Comment by jodygarnett** [comment]
Looks good two questions:

Can you confirm that when printed correctly with "full bleed" that the background will extend to the edge of the page? The ones we saw printed in Boston had a margin and I would like to confirm that this is a printing mistake, rather than a limitation of the files as provided.

Can you surround the screenshot in a computer frame (see the GRASS handout for an example).

Both of those are just questions, happy to merge this as provided and discuss the above.

**Comment by anitagraser** [comment]
Thanks for merging, Jody!

> Can you confirm that when printed correctly with "full bleed" that the background will extend to the edge of the page?

I'd expect it to be but I don't know for certain since this is not my area of expertise. I don't see any difference concerning printing comparing my Scribus approach to the SVGs we were provided. 

> Can you surround the screenshot in a computer frame (see the GRASS handout for an example).

If I can find the corresponding image file. I assume we should use the same computer frame image to get a consistent look.

**Comment by jodygarnett** [comment]
We may have to ask, or export the frame from original InDesign. Something to keep in mind.

**Comment by jodygarnett** [comment]
Of course the next day I get the laptop frame, available here: https://github.com/OSGeo/osgeo/tree/master/marketing/photos

**Comment by anitagraser** [comment]
Ok, I'll add it. I've been thinking about changing the screenshot anyway. Thanks Jody!

**Pull request merged**
