### PR TITLE
Prep banner stickers for foss4g booth

### PR DESCRIPTION
**Pull request by jodygarnett**
Follow on from https://github.com/OSGeo/osgeo/pull/244 here is my attempt at making sponsor logos at the correct scale to affix to our osgeo banner.

Because of the nature of our banners there should be a empty border around each sponsor logo for legibility; some of our banner designs have a large white area which is suitable for sponsor logo placement.

### CODE REVIEW

**Comment by jodygarnett** [comment]
I am not sure if we can make "fridge magnets", or if we can just print out in high quality and tape to the roll up banner :)

**Comment by jodygarnett** [comment]
@cvvergara  or @astroidex can you review please? :)

**Comment by astroidex** [comment]
Hello @jodygarnett. I would not print it like that.
- I would print it without the logos and then put the printed logo on the banner to allow the reuse of the banner.
- I would prefer to place the sponsors further down 
  - Our Sponsors: the x logos
  - in the dark blue section below the text Metadata Catalogs 
  - or below the OSGeo logo at the bottom

The Text "Empower everyone with..." could be bigger
  
Other banner
  - I prefer the designs with the OSGeo logo at the top
   - https://wiki.osgeo.org/w/images/9/92/Osgeo_roll_up.jpg
  -  or with the image at the top https://wiki.osgeo.org/wiki/File:Rollupbanner_compass.png

**Comment by jodygarnett** [comment]
If you look the pull request has the individual stickers; the preview just shows how they look at the same scale as the banner.

You can move the stickers on the banner where you like :)

**Comment by jodygarnett** [comment]
About printing banners:
- I am not changing the banner at all in this pull request, only making stickers the correct size (even if we print on paper and gluestick on).
- I always like the osgeo graphics that include a photo - and wish more groups would make that banner - with a picture from their country or city holding the event.
- if foss4gna wishes to provide a picture of Baltimore we can make a more specific banner in a separate PR :)

**Review by jodygarnett — COMMENTED** [review]
It seems the PR has the printable PDF files using names like `marketing/print/banner/camptocamp_sponsor@1x.pdf`.

This is not what is intended, we would like `camptocamp_sponsor.pdf` for example.

**Comment by jodygarnett** [comment]
> Hi @jodygarnett, a bit late comment. For the banner https://github.com/OSGeo/osgeo/pull/245/files#diff-5d691c748d6fde194d1c4273d73081c1c720e2b07bccfda955fed289ed615738 it would like to suggest to have ever one in one row. Same for open source geospatial. Maybe only 2 rows?
> 
> Empover every one with open source geospatial

I am not sure what that is, a horizontal banner? You can revisit with graphics designer when you get a chance....

**Pull request merged**
