### PR TITLE
OSGeo symbols set

### PR DESCRIPTION
**Pull request by nbozon**
Adds the symbols directory to /marketing/branding, containing source SVG documents and symbols webfont.

**This is a visual representation of the OSGeo projects and activities aimed at supplementing the Foundation branding material.**

A preview of the OSGeo symbols set is available here:
https://nbozon.github.io/OSGeo/symbols-set/

The 48 symbols fall into four categories:
- Foundation (OSGeo fundamentals represented by Variations on the Compass)
- Initiatives (mostly based on the compass shape too)
- Projects (derivated OSGeo project logos)
- Community (derivated Community projects logos)

The symbol set is made of two parts, both copyrighted OSGeo:
- The source SVG documents, licensed under CC-BY-SA 
- A cross-browser webfont, licensed under OFL.

All 48 symbols are made available as black SVG.
The 16 Foundation and Initiatives icons are also available in color, based on our brand guidelines, as shown below.

osgeo-symbols-set-color

### CODE REVIEW

**Comment by jodygarnett** [comment]
The GeoForAll color mark does not match the two toned look provided in the style guide as an example of a distinct brand. 
image

**Comment by jodygarnett** [comment]
@nbozon I am happy accept this PR and report the GeoForAll regression as a separate issue.

**Comment by jodygarnett** [comment]
@nbozon any activity here?

**Comment by nbozon** [comment]
@jodygarnett not recently, although these are in my todo list:
- Update pycsw logo 
- Correct GeoForAll colored logo
- Include Actinia logo
- Propose a logo for PROJ
- Propose a logo for Loader
- Propose a logo for pygeoapi

**Comment by jodygarnett** [comment]
As per discussion above, going to accept this PR and we can open issues to track some of the changes. 

I was just cautious as I do not want to see the "foundation and Initiatives icons" released in any official capacity (as they are off brand).

**Pull request merged**
