### PR TITLE
Update links to OSGeoLive logo

### PR DESCRIPTION
**Pull request by bencaradocdavies**
See also: https://trac.osgeo.org/osgeolive/ticket/2054

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
@cvvergara can you please review and merge this PR?

**Comment by bencaradocdavies** [comment]
@jodygarnett please review and merge this PR. Team is private so we do not know who else we can pester. OSGeoLive PSC has no known team members (despite have two on the OSGeo Board!).

**Comment by darkblue-b** [comment]
who has review permissions here?

**Comment by bencaradocdavies** [comment]
Anyone can review but only reviews by reviewers with write access are considered approval.

**Comment by bencaradocdavies** [comment]
@jodygarnett please merge this pull request. It fixes two links to the OSGeoLive-doc repo.

**Comment by bencaradocdavies** [comment]
Thanks @jodygarnett, much appreciated.

**Pull request merged**
